spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useUnicode=true&
      useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: testtest
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
spring.h2.console.enable: true
spring.flyway.enabled: true
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect

general_blog:
  title: DevPub
  subtitle: blogIT
  phone: +7 926 050-71-71
  email: egor.v.safonov@yandex.ru
  copyright: Сафонов Егор
  copyrightFrom: 2020